sudo: required

services:
  - docker

before_install:
  - docker build -t saivachandran/docker-react1  -f Dockerfile.dev 

script:

  - docker run -e CI=true  saivachandran/docker-react1 npm run test -- --coverage                 




