sudo: required

services:
  - docker

before_install:
  - docker build -t saivachandran/docker-react1  -f Dockerfile.dev 

script:

  - docker run -e CI=true  saivachandran/docker-react1 npm run test -- --coverage                 



deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react1 "
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-907225840730"
  bucket_path: "docker-react1"
  on:
    branch: master

 access_key_id: $AWS_ACCESS_KEY

 secret_access_key:
   secure: "$AWS_SECRET_KEY"      

